export const dashboardQueryKey = ['dashboard']
export const historyQueryKey = ['history']
export const expenseAnalyzerQueryKey = ['expense-analyzer']
export const expenseAnalyzerSummaryQueryKey = ['expense-analyzer', 'summary']
export const expenseAnalyzerNarrativeQueryKey = ['expense-analyzer', 'narrative']
export const usageQueryKey = ['usage']
export const notificationsQueryKey = ['notifications']
export const trackerQueryKey = ['trackers']
export const cashFlowForecastQueryKey = ['dashboard', 'forecast']
export const chatQueryKey = (insightId) => ['chat', insightId]
